# ASCII-Font › http://patorjk.com/software/taag/
#   ____    ____        _      __   __   _  __  U _____ u   ____     
#  |  _"\U |  _"\ u U  /"\  u  \ \ / /  |"|/ /  \| ___"|/U |  _"\ u  
# /| | | |\| |_) |/  \/ _ \/    \ V /   | ' /    |  _|"   \| |_) |/  
# U| |_| |\|  _ <    / ___ \   U_|"|_uU/| . \\u  | |___    |  _ <    
#  |____/ u|_| \_\  /_/   \_\    |_|    |_|\_\   |_____|   |_| \_\   
#   |||_   //   \\_  \\    >>.-,//|(_ ,-,>> \\,-.<<   >>   //   \\_  
#  (__)_) (__)  (__)(__)  (__)\_) (__) \.)   (_/(__) (__) (__)  (__) 

#------------------------------------------------------------------------------------------------------------

#
#      _____ _ __          _____      __  __  _
#     / ___/(_) /____     / ___/___  / /_/ /_(_)___  ____ ______
#     \__ \/ / __/ _ \    \__ \/ _ \/ __/ __/ / __ \/ __ `/ ___/
#    ___/ / / /_/  __/   ___/ /  __/ /_/ /_/ / / / / /_/ (__  )
#   /____/_/\__/\___/   /____/\___/\__/\__/_/_/ /_/\__, /____/
#                                                 /____/
#
# Title of your website
title: 'BSDK'

# The slogan describes your website and is used on homepage in <title> and other important places
slogan: 'Base structure of the distributed kernel'
